E2E: update github action to upload artifacts
otherwise it fails with
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```

and some changes to make yaml linter quiet.

Signed-off-by: karampok <karampok@gmail.com>